### ISSUE TITLE
No module named 'vdf._io'

### ISSUE THREAD

**Issue by lnfectedru** [Gobot1234/steam-ext-tf2#3]
I'm getting an error when trying to run example from README:
```
Traceback (most recent call last):
  File "d:/QuickScripts/tf2gc/main.py", line 2, in <module>
    from steam.ext import tf2
  File "C:\Users\lnfecteD\anaconda3\envs\tf2gc\lib\site-packages\steam\ext\tf2\__init__.py", line 1, in <module>
    import vdf
  File "C:\Users\lnfecteD\anaconda3\envs\tf2gc\lib\site-packages\vdf\__init__.py", line 17, in <module>
    from ._io import *
ModuleNotFoundError: No module named 'vdf._io'
```

Program that reproduces this error:
```
import steam
from steam.ext import tf2

bot = tf2.Bot(command_prefix="!")


@bot.event
async def on_ready() -> None:
    print("Bot is ready")

    
@bot.event
async def on_trade_accept(trade: steam.TradeOffer) -> None:
    refined_crafted = 0
    backpack = await bot.user.inventory(steam.TF2)
    scrap = backpack.filter_items("Scrap Metal")
    for scrap_triplet in steam.utils.chunk(scrap, 3):
        if len(scrap_triplet) != 3:
            break
        await bot.craft(scrap_triplet)

    backpack = await bot.user.inventory(steam.TF2)
    reclaimed = backpack.filter_items("Reclaimed Metal")
    for reclaimed_triplet in steam.utils.chunk(reclaimed, 3):
        if len(reclaimed_triplet) != 3:
            break
        await bot.craft(reclaimed_triplet)
        refined_crafted += 1

    print(f"Crafted {refined_crafted} Refined Metal")

bot.run("username", "password")
```

I'm using Python 3.7 and got the same error in 3.8

**Comment by Gobot1234** [comment]
You need to compile vdf yourself using c build tools which you can download here https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line.

**Comment by lnfectedru** [comment]
> You need to compile vdf yourself using c build tools which you can download here https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line.

Where can I find the source code that I have to compile?

**Comment by Gobot1234** [comment]
Just do pip install vdf3

**Comment by Gobot1234** [comment]
I'm assuming this has been fixed, feel free to reopen if not
